# Generated by Django 5.2.8 on 2025-11-29 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aprendiz',
            old_name='document_id',
            new_name='document',
        ),
    ]
